mvn package
echo $PIPELINE_BUILD_NUMBER
echo $PIPELINE_TRIGGER_MODE
echo $PIPELINE_BRANCH
echo $PIPELINE_CHECKIN_AUTHOR
echo $PIPELINE_REPOSITORY_GITHUB_URL
echo $PIPELINE_COMMIT_COMMENTS
echo $PIPELINE_START_TIME
echo $PIPELINE_MODULE_NAME
echo $PIPELINE_COMMIT_ID
echo $PIPELINE_BUILD_ID
echo $PIPELINE_TRIGGER_USER
 echo $*
 buildNumber=`echo $* |jq '.PIPELINE_BUILD_NUMBER'`
 echo $buildNumber >> BUILD_NUMBER
mkdir output
mv BUILD_NUMBER output
mv target/*.jar output

